import Final_Deliverable_Video from "./assets/Energyapp/Final_Deliverable_Video.mp4"

export default function EnergyApp() {
    return (
        <>
            <article>             
               <header>
        	<a href="/">
          		<input type="button" value={ "Home" }/>
        	</a>
        	<a href="/resume">
          		<input type="button" value={ "Resumé" }/>
        	</a>
			<a href="/Credentials">
          		<input type="button" value={ "Certifications" }/>
        	</a>
			<a href="/Projects">
          		<input type="button" value={ "Projects" }/>
        	</a>
      	</header>
                <h1>
                    Energy Usage In The United States: App Development
                </h1>
                <hr className="rounded"></hr>
                <br/>
                <h4>
                    Goal
                </h4>
                <p>
                    The goal of this project is to analyze energy usage trends in the United States across a 50-year period, focusing on the rise of renewable energy, state-level energy pricing, and the geographic and environmental factors affecting energy consumption. The objective is to develop visual and interactive tools to inform environmentalists, students, researchers, and policymakers on how energy is being produced and consumed across the country.
                  
                </p>

                <h4>
                    Procedure
                </h4>
                <p>
                Data Source: The group selected a dataset titled "Energy by State" from Google Public Data.
                </p>
                <p>
                    Key Research Questions & Visualization Plans:
                    <ul>
                        <li>
                            Questions:
                        </li>
                        <ul>
                            <li>
                                With the rise of renewable energy, which type of energy is being used the most in the U.S.?
                            </li>
                            <li>
                                In what states are certain energy types more or less expensive?
                            </li>
                              <li>
                                What states use the most of each energy type per person?
                            </li>
                              <li>
                                 What correlations, if any, are present between the average terrain of the state and the energy usage?
                            </li>
                        </ul>
                    </ul>
                    <ul>
                        <li>
                        Visualizations:
                        </li>
                        <ul>
                            <li>
                                Q1. U.S. Map, Graphs by energy type
                            </li>
                            <li>
                                Q2. Pie charts by energy type and state 
                            </li>
                             <li>
                                Q3. Side-by-side bar graphs, Y-point comparison
                            </li>
                            <li>
                                Q4. Terrain map, landmass overlays, statistical graphs
                            </li>
                        </ul>
                    </ul>


                    <ul>
                        <li>
                        User Interactions:
                        </li>
                        <ul>
                            <li>
                                Q1. Clickable map, dropdown menu, fuel type buttons
                            </li>
                            <li>
                                Q2. State selector, graph-type toggle buttons 
                            </li>
                             <li>
                                Q3. State selector, energy type buttons
                            </li>
                            <li>
                                Q4. Checkbox for terrain filters, graph generation button
                            </li>
                        </ul>
                    </ul>

                </p>

                <h4>
                    Findings
                </h4>
                <p>
                    A major takeaway from this project is that a concerning amount of energy is still being generated by fossil fuels, especially coal. Despite frequent messaging from media and industry suggesting progress toward clean energy, renewable sources still represent a very small fraction of total energy production.
                </p>

                <hr className="rounded"></hr>

                <span className="verticle">
                    <span className="horizontal">
                        <video src={ Final_Deliverable_Video } controls autoPlay muted/>
                    </span>
                </span>

                <hr className="rounded"></hr>
                <br/>
                <h4>
                    Tools Used
                </h4>
                <p>
                    
                Google Public Data – Energy by State, MATLAB, MATLAB APP 
                </p>

            </article>
        </>
    )
}